/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.it.pm2.receiptsplitter;

public class App {
    public String getGreeting() {
        return "Max Verstappen tu tu tu!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
