/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.it.pm2.receiptsplitter;

import ch.zhaw.it.pm2.receiptsplitter.service.Router;
import javafx.application.Application;
import javafx.stage.Stage;

import java.io.IOException;
import java.io.InputStream;
import java.util.logging.LogManager;
import java.util.logging.Logger;

public class Main {
    private static final Logger logger = Logger.getLogger(Main.class.getName());
    public static void main(String[] args) {
        configureLogging();
        logger.info("Starting the application");
        start();
    }

    private static void start() {
        Router router = new Router();
        try {
            Application.launch(router.getClass());
        } catch (Exception e) {
            logger.severe("An error occurred while trying to open the main window: " + e.getMessage());
        }
    }

    private static void configureLogging() {
        LogManager.getLogManager().reset();
        try {
            InputStream configStream = Main.class.getClassLoader().getResourceAsStream("logging.properties");
            if (configStream == null) {
                throw new IOException("Could not find logging.properties");
            }
            LogManager.getLogManager().readConfiguration(configStream);
        } catch (IOException e) {
            System.err.println("Could not setup logger configuration: " + e);
        }
    }
}
