/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.it.pm2.receiptsplitter;

import ch.zhaw.it.pm2.receiptsplitter.service.EmailService;
import ch.zhaw.it.pm2.receiptsplitter.service.Router;
import javafx.application.Application;
import javafx.stage.Stage;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.Arrays;
import java.util.logging.LogManager;
import java.util.logging.Logger;

public class Main extends Application {
    private static final Logger logger = Logger.getLogger(Main.class.getName());

    public static void main(String[] args) {
        configureLogging();
        logger.info("Starting the application");
        launch(args);
    }

    public void start(Stage stage) throws Exception {
        stage.setWidth(400);
        stage.setHeight(300);
        stage.setMinWidth(300);
        stage.setMinHeight(250);
        stage.setTitle("Receipt Splitter");

        Router router = new Router(stage);
        router.gotoScene(Pages.LOGIN_WINDOW);
    }

    private static void configureLogging() {
        File logDir = new File("logs");
        if (!logDir.exists()) {
            logDir.mkdir(); // Create the directory if it does not exist
        }
        LogManager.getLogManager().reset();
        try {
            InputStream configStream = Main.class.getClassLoader().getResourceAsStream("logging.properties");
            if (configStream == null) {
                throw new IOException("Could not find logging.properties");
            }
            LogManager.getLogManager().readConfiguration(configStream);
        } catch (IOException e) {
            System.err.println("Could not setup logger configuration: " + e);
        }
    }
}
